# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APSProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'Firebase/Core'
 pod 'Firebase/Auth'
 pod 'GoogleSignIn', '~> 5.0.2'
	

  target 'APSProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'APSProjectUITests' do
    # Pods for testing
  end

end
